"""Adding initial table structure

Revision ID: 2c13ffdfa3cc
Revises: f2902b4616ba
Create Date: 2021-02-20 15:06:06.973222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c13ffdfa3cc'
down_revision = 'f2902b4616ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreement',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('driver_id', sa.Text(), nullable=False),
    sa.Column('passenger_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('from', sa.Text(), nullable=False),
    sa.Column('to', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('driver_id', sa.Text(), nullable=True),
    sa.Column('passenger_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('driver_id', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('passenger_id', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'user', 'passenger', ['passenger_id'], ['id'])
    op.create_foreign_key(None, 'user', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'passenger_id')
    op.drop_column('user', 'driver_id')
    op.drop_table('order')
    op.drop_table('agreement')
    op.drop_table('passenger')
    op.drop_table('driver')
    # ### end Alembic commands ###
