"""small fix

Revision ID: 3bf4140680bd
Revises: 2c13ffdfa3cc
Create Date: 2021-02-20 15:53:57.276331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf4140680bd'
down_revision = '2c13ffdfa3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('from_', sa.Text(), nullable=False))
    op.drop_column('order', 'from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('from', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('order', 'from_')
    # ### end Alembic commands ###
