"""add cascade delete to the user tables

Revision ID: 4d7391e264e4
Revises: 361ab7ad84ed
Create Date: 2021-02-20 23:36:40.906772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7391e264e4'
down_revision = '361ab7ad84ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('driver_user_id_fkey', 'driver', type_='foreignkey')
    op.create_foreign_key(None, 'driver', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('passenger_user_id_fkey', 'passenger', type_='foreignkey')
    op.create_foreign_key(None, 'passenger', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passenger', type_='foreignkey')
    op.create_foreign_key('passenger_user_id_fkey', 'passenger', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'driver', type_='foreignkey')
    op.create_foreign_key('driver_user_id_fkey', 'driver', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
