"""add cascade delete to the other tables (again)

Revision ID: 71fa00181562
Revises: 8fde71fa39ec
Create Date: 2021-02-20 23:40:30.103883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fa00181562'
down_revision = '8fde71fa39ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_driver_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'driver', ['driver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_driver_id_fkey', 'order', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###
