"""add cascade delete to the other tables

Revision ID: 8fde71fa39ec
Revises: 4d7391e264e4
Create Date: 2021-02-20 23:38:38.592976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fde71fa39ec'
down_revision = '4d7391e264e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agreement_order_id_fkey', 'agreement', type_='foreignkey')
    op.drop_constraint('agreement_driver_id_fkey', 'agreement', type_='foreignkey')
    op.create_foreign_key(None, 'agreement', 'driver', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agreement', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blacklist_passenger_id_fkey', 'blacklist', type_='foreignkey')
    op.drop_constraint('blacklist_ban_driver_id_fkey', 'blacklist', type_='foreignkey')
    op.create_foreign_key(None, 'blacklist', 'driver', ['ban_driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blacklist', 'passenger', ['passenger_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_passenger_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'passenger', ['passenger_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_passenger_id_fkey', 'order', 'passenger', ['passenger_id'], ['id'])
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.drop_constraint(None, 'blacklist', type_='foreignkey')
    op.create_foreign_key('blacklist_ban_driver_id_fkey', 'blacklist', 'driver', ['ban_driver_id'], ['id'])
    op.create_foreign_key('blacklist_passenger_id_fkey', 'blacklist', 'passenger', ['passenger_id'], ['id'])
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.create_foreign_key('agreement_driver_id_fkey', 'agreement', 'driver', ['driver_id'], ['id'])
    op.create_foreign_key('agreement_order_id_fkey', 'agreement', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
