"""add geolocation2

Revision ID: a0ac333aaa63
Revises: b1d666d55f79
Create Date: 2021-02-21 05:37:17.665227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ac333aaa63'
down_revision = 'b1d666d55f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('geolocation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'geolocation')
    # ### end Alembic commands ###
