"""Fix incorrect reference

Revision ID: ac899aa2f607
Revises: 3bf4140680bd
Create Date: 2021-02-20 16:35:48.766271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac899aa2f607'
down_revision = '3bf4140680bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('order_id', sa.Text(), nullable=False))
    op.drop_constraint('agreement_passenger_id_fkey', 'agreement', type_='foreignkey')
    op.create_foreign_key(None, 'agreement', 'order', ['order_id'], ['id'])
    op.drop_column('agreement', 'passenger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('passenger_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.create_foreign_key('agreement_passenger_id_fkey', 'agreement', 'passenger', ['passenger_id'], ['id'])
    op.drop_column('agreement', 'order_id')
    # ### end Alembic commands ###
