"""add field for image

Revision ID: aecb7668239b
Revises: ac899aa2f607
Create Date: 2021-02-20 17:45:40.743183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecb7668239b'
down_revision = 'ac899aa2f607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'image')
    # ### end Alembic commands ###
